### ISSUE TITLE
Provide guidence on using steps correctly

### ISSUE THREAD

**Issue by FreeMasen** [sersoft-gmbh/os-version-action#69]
In the provided example, the entry does not contain an `id` property which is required to use  `{{ steps.<step-id>.outputs.<property> }}` , GHA doesn't seem to use a kabob-cased version of the name for this by default and it could lead to some confusion. Either calling this out in the readme or adding an ID property to the example would be nice. I can open a PR if you have a preference

**Comment by ffried** [comment]
@FreeMasen I'm not sure I follow. The example in the README _does_ have an `id`:
<img width="759" alt="image" src="https://github.com/sersoft-gmbh/os-version-action/assets/1689782/de07b634-4fcd-4010-9255-195fc37a706e">

We use this exact setup in our actions and it works fine. Can you elaborate on what isn't working for you?

**Comment by FreeMasen** [comment]
OMG, I am so sorry. I clearly missed this when trying to use your project 😳
